/* Generated by AN DISI Unibo */ 
package it.unibo.fridge

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Fridge ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						solve("consult('fridgeInit.pl')","") //set resVar	
						println("&&&  fridge starting, initial state as follows")
						solve("showState","") //set resVar	
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("waitCmd") { //this:State
					action { //it:State
						println("&&&  fridge waiting for command")
					}
					 transition(edgeName="t015",targetState="prepareTask",cond=whenDispatch("prepare"))
					transition(edgeName="t016",targetState="addTask",cond=whenDispatch("add"))
					transition(edgeName="t017",targetState="showTask",cond=whenDispatch("showFridgeState"))
					transition(edgeName="t018",targetState="checkAvailability",cond=whenDispatch("isAvailable"))
				}	 
				state("prepareTask") { //this:State
					action { //it:State
						solve("consult('prepareFoodList.pl')","") //set resVar	
						println("&&&  fridge received prepare, handing over food")
						solve("prepare","") //set resVar	
						println("&&&  fridge state modified, now as follows")
						solve("showState","") //set resVar	
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("addTask") { //this:State
					action { //it:State
						var code ="" 
						if( checkMsgContent( Term.createTerm("add(ARG)"), Term.createTerm("add(C)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								code = payloadArg(0)
								println("&&& fridge received add, checking availability of food with code $code")
								solve("isThere('$code')","") //set resVar	
								if(currentSolution.isSuccess()) { solve("get('$code',1)","") //set resVar	
								if(currentSolution.isSuccess()) { println("Add possibile, fridge informa RBR")
								forward("add", "add()" ,"butlermind" ) 
								 }
								else
								{ println("Add impossibile, quantita' insufficiente nel frigo")
								forward("modelUpdate", "modelUpdate(fridge,addImpossibleWarning)" ,"resourcemodel" ) 
								 }
								 }
								else
								{ println("Add impossibile, code inesistente o cibo terminato")
								forward("modelUpdate", "modelUpdate(fridge,addImpossibleWarning)" ,"resourcemodel" ) 
								 }
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("showTask") { //this:State
					action { //it:State
						println("&&&  fridge received showState, executing")
						solve("showState","") //set resVar	
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
				state("checkAvailability") { //this:State
					action { //it:State
						println("&&&  fridge received availability check, executing")
						var code = "" 
						if( checkMsgContent( Term.createTerm("isAvalaible(CODE)"), Term.createTerm("isAvailable(CODE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								code = payloadArg(0)
								solve("isThere('$code')","") //set resVar	
								if(currentSolution.isSuccess()) { println("Food available")
								forward("modelUpdate", "modelUpdate(fridge,foodAvailable)" ,"resourcemodel" ) 
								 }
								else
								{ println("Food not found")
								forward("modelUpdate", "modelUpdate(fridge,foodNotFound)" ,"resourcemodel" ) 
								 }
						}
					}
					 transition( edgeName="goto",targetState="waitCmd", cond=doswitch() )
				}	 
			}
		}
}
